language: go
sudo: false

go:
- 1.x
- 1.1.x
- 1.2.x
- 1.3.x
- 1.4.x
- 1.5.x
- 1.6.x
- 1.7.x
- 1.8.x
- master

before_install:
  # Needed for Go 1.4.x :'(
  - go get golang.org/x/tools/cmd/cover

script:
  - ./codecov_test.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)

matrix:
  allow_failures:
  - go: master