language: go
sudo: false

env:
  global:
    - GOLANGCI_LINT_VERSION=v1.10.2
    - DEP_VERSION=v0.5.0

matrix:
  allow_failures:
  - go: master
  include:
  # Supported versions of Go: https://golang.org/dl/
  - go: "1.10.x"
  - go: "1.11.x"
  - go: master

before_install:
  - curl -L -s https://github.com/golang/dep/releases/download/$DEP_VERSION/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s -- -b $GOPATH/bin $GOLANGCI_LINT_VERSION

install:
  - dep ensure -vendor-only

before_script:
  - golangci-lint run

script:
  - ./codecov_test.sh

after_success:
  - bash <(curl -s https://codecov.io/bash) -X fix
