language: go
sudo: false

matrix:
  allow_failures:
  - go: master
  include:
  # Supported versions of Go: https://golang.org/dl/
  # Note: Go 1.1 is no longer available
  - go: 1.x
  - go: 1.2.x
    env: NO_GOLINT=true
  - go: 1.3.x
    env: NO_GOLINT=true
  - go: 1.4.x
    env: NO_GOLINT=true NO_VET=true GO_GET_COVER=true
  - go: 1.5.x
    env: NO_GOLINT=true
  - go: 1.6.x
  - go: 1.7.x
  - go: 1.8.x
  - go: 1.9.x
  - go: master

before_install:
  - if [ $GO_GET_COVER ]; then go get golang.org/x/tools/cmd/cover; fi
  - if [ "${NO_GOLINT}" != "true" ]; then go get github.com/golang/lint/golint; fi

before_script:
  - if [ "${NO_VET}" != "true" ]; then go vet ./...; fi
  - if [ "${NO_GOLINT}" != "true" ]; then golint ./...; fi

script:
  - ./codecov_test.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
